- hosts: wp         # 공통적인 role은 common role로 지정
  become: yes
  roles: 
    - common

- hosts: wp-nfs     # nfs service 진행할 role 설정
  become: yes
  roles:
    - nfs

- hosts: wp-db      # MariaDB 중 초기 동일 설정 role 지정
  become: yes
  roles: 
    - mariadb

- hosts: node3      # MariaDB 동기화(Galera cluster)를 위한 role 지정
  become: yes
  roles:
    - mariadb1

- hosts: node4      # MariaDB 동기화(Galera cluster)를 위한 role 지정
  become: yes
  roles:
    - mariadb2

- hosts: wp-web     # apache service 설치할 node의 role 지정
  become: yes
  roles: 
    - apache

- hosts: wp-lb      # haproxy service 설치할 node의 role 지정
  become: yes
  roles: 
    - haproxy
