---
- block:
  - name: Install epel-release
    yum: 
      name: epel-release 
      state: latest
  - name: Install libsemanage-python for seboolean
    yum: 
      name: libsemanage-python 
      state: latest
  when: ansible_distribution == 'CentOS'

- block:
  - name: Update apt cache
    apt:
      update_cache: yes
  when: ansible_distribution == 'Ubuntu'