- name: Add yum_repository for mariadb            # MariaDB repository 추가
  yum_repository: 
    name: MariaDB 
    baseurl: "{{ mariadb['repo']['baseurl'] }}"
    gpgkey: "{{ mariadb['repo']['gpgkey'] }}"
    gpgcheck: 1 
    description: MariaDB
- name: Install mariadb                           # MariaDB 설치
  yum: 
    name: MariaDB-server
    enablerepo: MariaDB 
    state: latest
- name: Install library for DB                    # MariaDB 관리용 library 설치
  yum: 
    name: MySQL-python 
    state: latest
- name: semanage package install
  yum:
    name: policycoreutils-python
    state: installed
- name: Start mariadb                             # MariaDB service 시작
  service: 
    name: mariadb 
    state: started
- name: Open mariadb port                         # MariaDB 사용 port 해제
  firewalld: 
    port: "{{ mariadb['port'] }}/tcp"
    permanent: yes 
    state: enabled 
    immediate: yes
- name: firewalld open galera port                # galera cluster 사용 port 해제
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: [ 4444/tcp,4567/tcp,4568/tcp,4567/udp ]
- name: semanage port (tcp)                       # semanage port 해제
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: mysqld_port_t
    state: present
  with_items: [ 4444,4567,4568 ]
- name: semanage port (udp)
  seport:
    ports: 4567
    proto: udp
    setype: mysqld_port_t
    state: present
- name: Set root password                         # root password 변경
  mysql_user: 
    login_user: root 
    login_password: ''
    user: root 
    password: dkagh1. 
    state: present
