---
- name: Install haproxy                         # haproxy package 설치
  apt:
    name: haproxy
    state: latest
    update_cache: yes
- name: Set facts for haproxy public ip         # 설정파일에 작성될 변수 지정
  set_fact:
    haproxy_public_ip: "{{ ansible_ens3.ipv4.address }}"
- name: Delegate collecting facts for wordpress1
  setup:
  delegate_to: node1
- name: Set facts for wordpress1 private ip
  set_fact:
    wordpress1_private_ip: "{{ ansible_eth1.ipv4.address }}"
- name: Delegate collecting facts for wordpress2
  setup:
  delegate_to: node2
- name: Set facts for wordpress2 private ip
  set_fact:
    wordpress2_private_ip: "{{ ansible_eth1.ipv4.address }}"
- name: Copy haproxy configuration             # 설정파일 복사
  template:
    src: ubuntu/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - Restart haproxy service