- name: gleara ip setting(node3)                  # 설정파일에 작성될 변수 세팅
  setup:
  delegate_to: node3
- name: set fact node3 ip
  set_fact:
    node3_ip: "{{ ansible_eth1.ipv4.address }}"
- name: gleara ip setting(node4)
  setup:
  delegate_to: node4
- name: set fact node4 ip
  set_fact:
    node4_ip: "{{ ansible_eth1.ipv4.address }}"
- name: Copy mariadb configuration                # galera cluster 설정파일 복사
  template:
    src: galera3.cnf.j2
    dest: /etc/my.cnf.d/galera.cnf
- name: mariadb service stop
  service:
    name: mariadb
    state: stopped
- name: semanage permissive
  selinux_permissive:
    name: mysqld_t
    permissive: true
- name: galera service start
  command: "galera_new_cluster"
- name: mariadb enabled
  service:
    name: mariadb
    enabled: true
- name: Active seboolean for mysql                # selinux 해제
  seboolean: 
    name: mysql_connect_any 
    state: yes 
    persistent: yes