apiVersion: v1
kind: Pod
metadata:
    name: mynapp-pod
    namespace: development
spec:
    containers:
      - image: leeseonhyo817/myweb
        name: mynapp-ns-container
        ports:
        - containerPort: 8080
          protocol: TCP