apiVersion: v1
kind: ReplicationController
metadata:
  name: mynapp-rc
spec:
  replicas: 3
  selector:
    app: mynapp-rc
  template:
    metadata:
      labels:
        app: mynapp-rc
    spec:
      containers:
        - name: mynapp-rc
          image: leeseonhyo817/myweb
          ports:
          - containerPort: 8080
            protocol: TCP