apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-liveness-http
spec:
  containers:
    - image: httpd:latest
      name: mynapp-container-livenesss-http
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80