apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-liveness-http
spec:
  containers:
    - name: mynapp-container-liveness-http
      image: httpd:latest
      ports:
        - containerPort: 80
      livenessProbe:
        tcpSocket:
          port: 80