apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mynapp-ds
spec:
  selector:
    matchLables:
      app: mynapp-ds
  template:
    metadata:
      labels:
        app: mynapp-ds
    spec:
      nodeSelector:
        node: development
      containers:
        - name: mynapp
          image: leeseonhyo817/myweb
          ports:
            - containerPort: 8080