apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mynapp-cjob-po-replace
spec:
  schedule: "*/2 * * * *"
  startingDeadlineSeconds: 30
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mynapp-cjob-po-replace
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mynapp
              image: busybox
              command: ["sleep","180"]