apiVersion: batch/v1
kind: Job
metadata:
  name: mynapp-job-comp-para
spec:
  completions: 6
  parallelism: 3
  template:
    metadata:
      labels:
        app: mynapp-job-comp-para
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mynapp
          image: busybox
          command: ["sleep","60"]