apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mynapp-cjob-po-forbid
spec:
  schedule: "*/2 * * * *"
  startingDeadlineSeconds: 30
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mynapp-cjob-po-forbid
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mynapp
              image: busybox
              command: ["sleep","180"]