---
apiVersion: v1
kind: Service
metadata:
  name: mynapp-svc-myweb1
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mynapp-rs-myweb1
---
apiVersion: v1
kind: Service
metadata:
  name: mynapp-svc-myweb2
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mynapp-rs-myweb2
---
apiVersion: v1
kind: Service
metadata:
  name: mynapp-svc-web1
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mynapp-rs-web1
---
apiVersion: v1
kind: Service
metadata:
  name: mynapp-svc-web2
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mynapp-rs-web2