apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: Headless-ReplicaSet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynapp-headless-rs
  template:
    metadata:
      labels:
        app: mynapp-headless-rs
    spec:
      containers:
        - name: mynapp
          image: leeseonhyo817/myweb
          ports:
            - containerPort: 8080