apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-fortune-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynapp-fortune-rs
  template:
    metadata:
      labels:
        app: mynapp-fortune-rs
    spec:
      containers:
        - name: web-server
          image: nginx:alpine
          volumeMounts:
            - name: web-fortune
              mountPath:
                /usr/share/nginx/html
              readOnly: true
          ports:
            - containerPort: 80
        - name: html-generator
          image: leeseonhyo817/fortune
          volumeMounts:
            - name: web-fortune
              mountPath: /var/htdocs
      volumes:
        - name: web-fortune
          emptyDir: {}