apiVersion: v1
kind: PersistentVolume
metadata:
  name: mynapp-nfs-pv
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports/nfs-vols
    server: kube-master1