apiVersion: v1
kind: Pod
metadata:
  name: mynapp-env-pod
spec:
  containers:
    - name: mynapp
      image: leeseonhyo817/myweb:customport
      env:
        - name: NODE_PORT
          value: "8088"
      ports:
        - containerPort: 8088
          protocol: TCP