apiVersion: v1
kind: Pod
metadata:
  name: mynapp-cm-pod
spec:
  containers:
    - image: leeseonhyo817/myweb:customport
      name: mynapp
      env:
        - name: NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: mynapp-pod-options
              key: nodeport
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: mynapp-pod-options
              key: message
      args:
        - $(MESSAGE)
      ports:
        - containerPort: 8080
          protocol: TCP