apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-cm-compress-subPath
spec:
  containers:
    - image: nginx
      name: mynapp-compress
      volumeMounts:
        - name: nginx-compress-config
          mountPath: /etc/nginx/conf.d/nginx-gzip.conf
          subPath: nginx-gzip.conf
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: nginx-compress-config
      configMap:
        name: nginx-gzip-config