apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-req
spec:
  containers:
    - image: leeseonhyo817/myweb:v1
      name: mynapp
      resources:
        requests:
          cpu: 200m
          memory: 10Mi