apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-lim
spec:
  containers:
    - image: leeseonhyo817/myweb:v1
      name: mynapp
      resources:
        limits:
          cpu: 0.5
          memory: 20Mi