apiVersion: v1
kind: Pod
metadata:
  name: mynapp-pod-huge-req
spec:
  containers:
    - image: leeseonhyo817/myweb:v1
      name: mynapp
      resources:
        requests:
          cpu: 4000m
          memory: 4Gi