apiVersion: v1
kind: ResourceQuota
metadata:
  name: mynapp-quota-storage
spec:
  hard:
    requests.storage: 10Gi
    rook-ceph-block.storageclass.storage.k8s.io/requests.storage: 10Gi
    rook-cephfs.storageclass.storage.k8s.io/requests.storage: 20Gi