apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-nn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynapp-rs-nn
  template:
    metadata:
      labels:
        app: mynapp-rs-nn
    spec:
      nodeName: kube-node1
      containers:
        - name: mynapp
          image: leeseonhyo817/myweb:v1