apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynapp-rs-cordon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynapp-rs-cordon
  template:
    metadata:
      labels:
        app: mynapp-rs-cordon
    spec:
      containers:
        - name: mynapp
          image: leeseonhyo817/myweb:v1